SET(ASSIMP_FOUND FALSE)
SET(ASSIMP_INCLUDE_DIRS)
SET(ASSIMP_LIBRARIES)

SET(SEARCH_PATHS
  $ENV{ProgramFiles}/assimp/include
  $ENV{SystemDrive}/assimp/include
  $ENV{ProgramFiles}/assimp
  $ENV{SystemDrive}/assimp
  /usr/include
  /usr/local/include/
  )
IF(ASSIMP_ROOT)
  SET(SEARCH_PATHS
    ${ASSIMP_ROOT}
    ${ASSIMP_ROOT}/include
    ${SEARCH_PATHS}
    )
ENDIF()

FIND_PATH(ASSIMP_INCLUDE_DIRS
  NAMES assimp/ai_assert.h
  PATHS ${SEARCH_PATHS}
  NO_DEFAULT_PATH)
IF(NOT ASSIMP_INCLUDE_DIRS)  # now look in system locations
  FIND_PATH(ASSIMP_INCLUDE_DIRS NAMES assimp/ai_assert.h)
ENDIF(NOT ASSIMP_INCLUDE_DIRS)

SET(ASSIMP_LIBRARY_DIRS /
  usr/lib64
  /usr/lib
  /usr/local/lib
  )
  
IF(ASSIMP_ROOT)
  SET(ASSIMP_LIBRARY_DIRS ${ASSIMP_LIBRARY_DIRS} ${ASSIMP_ROOT})
  IF(EXISTS "${ASSIMP_ROOT}/lib64")
    SET(ASSIMP_LIBRARY_DIRS ${ASSIMP_LIBRARY_DIRS} ${ASSIMP_ROOT}/lib64)
  ENDIF()
ENDIF()

# ASSIMP
# Without system dirs
FIND_LIBRARY(ASSIMP_LIBRARY
  NAMES assimp
  PATHS ${ASSIMP_LIBRARY_DIRS}
  NO_DEFAULT_PATH
  )
IF(NOT ASSIMP_LIBRARY)  # now look in system locations
  FIND_LIBRARY(ASSIMP_LIBRARY NAMES assimp)
ENDIF(NOT ASSIMP_LIBRARY)

SET(ASSIMP_LIBRARIES)
IF(ASSIMP_LIBRARY)
  SET(ASSIMP_LIBRARIES ${ASSIMP_LIBRARY})
ENDIF()

IF(ASSIMP_INCLUDE_DIRS AND ASSIMP_LIBRARIES)
  SET(ASSIMP_FOUND TRUE)
  IF(NOT ASSIMP_FIND_QUIETLY)
    MESSAGE(STATUS "Found ASSIMP: headers at ${ASSIMP_INCLUDE_DIRS}, libraries at ${ASSIMP_LIBRARIES}")
  ENDIF(NOT ASSIMP_FIND_QUIETLY)
ELSE(ASSIMP_INCLUDE_DIRS AND ASSIMP_LIBRARIES)
  SET(ASSIMP_FOUND FALSE)
  IF(ASSIMP_FIND_REQUIRED)
    MESSAGE(STATUS "ASSIMP not found")
  ENDIF(ASSIMP_FIND_REQUIRED)
ENDIF(ASSIMP_INCLUDE_DIRS AND ASSIMP_LIBRARIES)

MARK_AS_ADVANCED(ASSIMP_INCLUDE_DIRS ASSIMP_LIBRARIES)
